/*
 * WarehouseProductPanel.java
 *
 * Created on Понеделник, 2008, Май 5, 10:55
 */

package com.cosmos.acacia.crm.gui.warehouse;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.ejb.EJB;

import org.jdesktop.application.Action;
import org.jdesktop.beansbinding.AbstractBindingListener;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.PropertyStateEvent;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;

import com.cosmos.acacia.crm.bl.impl.WarehouseListRemote;
import com.cosmos.acacia.crm.data.SimpleProduct;
import com.cosmos.acacia.crm.data.WarehouseProduct;
import com.cosmos.acacia.crm.gui.ProductsListPanel;
import com.cosmos.acacia.gui.AcaciaLookupProvider;
import com.cosmos.acacia.gui.AcaciaToStringConverter;
import com.cosmos.acacia.gui.BaseEntityPanel;
import com.cosmos.acacia.gui.EntityFormButtonPanel;
import com.cosmos.acacia.gui.EntityFormButtonPanel.Button;
import com.cosmos.beansbinding.EntityProperties;
import com.cosmos.beansbinding.PropertyDetails;
import com.cosmos.swingb.DialogResponse;

/**
 *
 * @author  jchan
 */
public class WarehouseProductPanel extends BaseEntityPanel {

    @EJB
    private WarehouseListRemote formSession;

    private WarehouseProduct entity;
    private BindingGroup bindGroup;
    private EntityProperties entProps;

    /** Creates new form WarehouseProductPanel */
    public WarehouseProductPanel(WarehouseProduct warehouseProduct, BigInteger parentId) {
        super(parentId);
        this.entity = warehouseProduct;
        init();
    }

    @Override
    protected void init()
    {
        initComponents();
        super.init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productField = new com.cosmos.acacia.gui.AcaciaLookup();
        warehouseField = new com.cosmos.acacia.gui.AcaciaLookup();
        jBPanel1 = new com.cosmos.swingb.JBPanel();
        jBLabel3 = new com.cosmos.swingb.JBLabel();
        qtyInStockField = new com.cosmos.swingb.JBTextField();
        jBLabel5 = new com.cosmos.swingb.JBLabel();
        qtyFreeField = new com.cosmos.swingb.JBTextField();
        jBLabel6 = new com.cosmos.swingb.JBLabel();
        qtyOrderedField = new com.cosmos.swingb.JBTextField();
        jBLabel7 = new com.cosmos.swingb.JBLabel();
        qtyReservedField = new com.cosmos.swingb.JBTextField();
        jBLabel8 = new com.cosmos.swingb.JBLabel();
        qtySoldField = new com.cosmos.swingb.JBTextField();
        jBLabel13 = new com.cosmos.swingb.JBLabel();
        qtyDueField = new com.cosmos.swingb.JBTextField();
        jBPanel2 = new com.cosmos.swingb.JBPanel();
        jBLabel4 = new com.cosmos.swingb.JBLabel();
        minQtyField = new com.cosmos.swingb.JBTextField();
        jBLabel9 = new com.cosmos.swingb.JBLabel();
        maxQtyField = new com.cosmos.swingb.JBTextField();
        jBLabel10 = new com.cosmos.swingb.JBLabel();
        defaultQtyField = new com.cosmos.swingb.JBTextField();
        jBLabel15 = new com.cosmos.swingb.JBLabel();
        minFromProductField = new com.cosmos.swingb.JBLabel();
        maxFromProductField = new com.cosmos.swingb.JBLabel();
        defaultFromProductField = new com.cosmos.swingb.JBLabel();
        jBLabel14 = new com.cosmos.swingb.JBLabel();
        deliveryTimeField = new com.cosmos.swingb.JBTextField();
        jBPanel4 = new com.cosmos.swingb.JBPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesField = new com.cosmos.swingb.JBTextPane();
        entityFormButtonPanel1 = new com.cosmos.acacia.gui.EntityFormButtonPanel();
        jBButton1 = new com.cosmos.swingb.JBButton();
        jBLabel2 = new com.cosmos.swingb.JBLabel();
        jBLabel1 = new com.cosmos.swingb.JBLabel();
        salesPriceField = new com.cosmos.swingb.JBTextField();
        jBLabel11 = new com.cosmos.swingb.JBLabel();

        setName("Form"); // NOI18N

        productField.setName("productField"); // NOI18N

        warehouseField.setName("warehouseField"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.cosmos.acacia.crm.gui.AcaciaApplication.class).getContext().getResourceMap(WarehouseProductPanel.class);
        jBPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jBPanel1.border.title"))); // NOI18N
        jBPanel1.setName("jBPanel1"); // NOI18N

        jBLabel3.setText(resourceMap.getString("jBLabel3.text")); // NOI18N
        jBLabel3.setName("jBLabel3"); // NOI18N

        qtyInStockField.setEditable(false);
        qtyInStockField.setText(resourceMap.getString("qtyInStockField.text")); // NOI18N
        qtyInStockField.setName("qtyInStockField"); // NOI18N
        qtyInStockField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyInStockFieldActionPerformed(evt);
            }
        });

        jBLabel5.setText(resourceMap.getString("jBLabel5.text")); // NOI18N
        jBLabel5.setName("jBLabel5"); // NOI18N

        qtyFreeField.setEditable(false);
        qtyFreeField.setText(resourceMap.getString("qtyFreeField.text")); // NOI18N
        qtyFreeField.setName("qtyFreeField"); // NOI18N

        jBLabel6.setText(resourceMap.getString("jBLabel6.text")); // NOI18N
        jBLabel6.setName("jBLabel6"); // NOI18N

        qtyOrderedField.setEditable(false);
        qtyOrderedField.setText(resourceMap.getString("qtyOrderedField.text")); // NOI18N
        qtyOrderedField.setName("qtyOrderedField"); // NOI18N

        jBLabel7.setText(resourceMap.getString("jBLabel7.text")); // NOI18N
        jBLabel7.setName("jBLabel7"); // NOI18N

        qtyReservedField.setEditable(false);
        qtyReservedField.setText(resourceMap.getString("qtyReservedField.text")); // NOI18N
        qtyReservedField.setName("qtyReservedField"); // NOI18N

        jBLabel8.setText(resourceMap.getString("jBLabel8.text")); // NOI18N
        jBLabel8.setName("jBLabel8"); // NOI18N

        qtySoldField.setEditable(false);
        qtySoldField.setText(resourceMap.getString("qtySoldField.text")); // NOI18N
        qtySoldField.setName("qtySoldField"); // NOI18N

        jBLabel13.setText(resourceMap.getString("jBLabel13.text")); // NOI18N
        jBLabel13.setName("jBLabel13"); // NOI18N

        qtyDueField.setEditable(false);
        qtyDueField.setText(resourceMap.getString("qtyDueField.text")); // NOI18N
        qtyDueField.setName("qtyDueField"); // NOI18N

        javax.swing.GroupLayout jBPanel1Layout = new javax.swing.GroupLayout(jBPanel1);
        jBPanel1.setLayout(jBPanel1Layout);
        jBPanel1Layout.setHorizontalGroup(
            jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBPanel1Layout.createSequentialGroup()
                        .addComponent(jBLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jBPanel1Layout.createSequentialGroup()
                        .addComponent(jBLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jBPanel1Layout.createSequentialGroup()
                        .addComponent(jBLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jBPanel1Layout.createSequentialGroup()
                        .addComponent(jBLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(jBPanel1Layout.createSequentialGroup()
                        .addComponent(jBLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(jBPanel1Layout.createSequentialGroup()
                        .addComponent(jBLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qtyDueField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(qtySoldField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(qtyReservedField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(qtyOrderedField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(qtyFreeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtyInStockField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jBPanel1Layout.setVerticalGroup(
            jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel1Layout.createSequentialGroup()
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyInStockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyFreeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyOrderedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyReservedField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtySoldField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyDueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jBPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jBPanel2.border.title"))); // NOI18N
        jBPanel2.setName("jBPanel2"); // NOI18N

        jBLabel4.setText(resourceMap.getString("jBLabel4.text")); // NOI18N
        jBLabel4.setName("jBLabel4"); // NOI18N

        minQtyField.setText(resourceMap.getString("minQtyField.text")); // NOI18N
        minQtyField.setName("minQtyField"); // NOI18N

        jBLabel9.setText(resourceMap.getString("jBLabel9.text")); // NOI18N
        jBLabel9.setName("jBLabel9"); // NOI18N

        maxQtyField.setText(resourceMap.getString("maxQtyField.text")); // NOI18N
        maxQtyField.setName("maxQtyField"); // NOI18N

        jBLabel10.setText(resourceMap.getString("jBLabel10.text")); // NOI18N
        jBLabel10.setName("jBLabel10"); // NOI18N

        defaultQtyField.setText(resourceMap.getString("defaultQtyField.text")); // NOI18N
        defaultQtyField.setName("defaultQtyField"); // NOI18N

        jBLabel15.setText(resourceMap.getString("jBLabel15.text")); // NOI18N
        jBLabel15.setName("jBLabel15"); // NOI18N

        minFromProductField.setText(resourceMap.getString("minFromProductField.text")); // NOI18N
        minFromProductField.setAlignmentX(0.5F);
        minFromProductField.setName("minFromProductField"); // NOI18N

        maxFromProductField.setText(resourceMap.getString("maxFromProductField.text")); // NOI18N
        maxFromProductField.setName("maxFromProductField"); // NOI18N

        defaultFromProductField.setText(resourceMap.getString("defaultFromProductField.text")); // NOI18N
        defaultFromProductField.setName("defaultFromProductField"); // NOI18N

        javax.swing.GroupLayout jBPanel2Layout = new javax.swing.GroupLayout(jBPanel2);
        jBPanel2.setLayout(jBPanel2Layout);
        jBPanel2Layout.setHorizontalGroup(
            jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jBLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jBLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(defaultQtyField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(minQtyField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(maxQtyField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(defaultFromProductField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addComponent(maxFromProductField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addComponent(minFromProductField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jBPanel2Layout.setVerticalGroup(
            jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel2Layout.createSequentialGroup()
                .addComponent(jBLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minFromProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxFromProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultFromProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBLabel14.setText(resourceMap.getString("jBLabel14.text")); // NOI18N
        jBLabel14.setName("jBLabel14"); // NOI18N

        deliveryTimeField.setText(resourceMap.getString("deliveryTimeField.text")); // NOI18N
        deliveryTimeField.setName("deliveryTimeField"); // NOI18N

        jBPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jBPanel4.border.title"))); // NOI18N
        jBPanel4.setName("jBPanel4"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        notesField.setName("notesField"); // NOI18N
        jScrollPane1.setViewportView(notesField);

        javax.swing.GroupLayout jBPanel4Layout = new javax.swing.GroupLayout(jBPanel4);
        jBPanel4.setLayout(jBPanel4Layout);
        jBPanel4Layout.setHorizontalGroup(
            jBPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addContainerGap())
        );
        jBPanel4Layout.setVerticalGroup(
            jBPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        entityFormButtonPanel1.setName("entityFormButtonPanel1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.cosmos.acacia.crm.gui.AcaciaApplication.class).getContext().getActionMap(WarehouseProductPanel.class, this);
        jBButton1.setAction(actionMap.get("productPricingAction")); // NOI18N
        jBButton1.setText(resourceMap.getString("jBButton1.text")); // NOI18N
        jBButton1.setName("jBButton1"); // NOI18N

        jBLabel2.setText(resourceMap.getString("jBLabel2.text")); // NOI18N
        jBLabel2.setName("jBLabel2"); // NOI18N

        jBLabel1.setText(resourceMap.getString("jBLabel1.text")); // NOI18N
        jBLabel1.setName("jBLabel1"); // NOI18N

        salesPriceField.setEditable(false);
        salesPriceField.setText(resourceMap.getString("salesPriceField.text")); // NOI18N
        salesPriceField.setName("salesPriceField"); // NOI18N

        jBLabel11.setText(resourceMap.getString("jBLabel11.text")); // NOI18N
        jBLabel11.setName("jBLabel11"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entityFormButtonPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jBLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productField, 0, 345, Short.MAX_VALUE))
                            .addComponent(jBPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jBLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(warehouseField, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jBLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                        .addComponent(jBLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(salesPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                        .addComponent(deliveryTimeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warehouseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deliveryTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entityFormButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void qtyInStockFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyInStockFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyInStockFieldActionPerformed

    @Override
    public void performSave(boolean closeAfter) {
        entity = getFormSession().saveWarehouseProduct(entity);
        setDialogResponse(DialogResponse.SAVE);
        setSelectedValue(entity);
        if (closeAfter)
            close();
    }

    @Override
    public BindingGroup getBindingGroup() {
        return bindGroup;
    }

    @Override
    public Object getEntity() {
        return entity;
    }

    @Override
    public EntityFormButtonPanel getButtonPanel() {
        return entityFormButtonPanel1;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected void initData() {

        entProps = getFormSession().getWarehouseProductEntityProperties();
        PropertyDetails propDetails;

        bindGroup = new BindingGroup();

        //product field
        propDetails = entProps.getPropertyDetails("product");
        Binding productBinding = productField.bind(new AcaciaLookupProvider() {

            @Override
            public Object showSelectionControl() {
                return onChooseProduct();
            }

        }, bindGroup,
        entity,
        propDetails,
        "${productName}",
        UpdateStrategy.READ_WRITE);
        productBinding.addBindingListener(new AbstractBindingListener() {
            @Override
            public void bindingBecameBound(Binding binding) {
                updateProductQuantities(binding);
            }
            @SuppressWarnings("unchecked")
            @Override
            public void targetChanged(Binding binding, PropertyStateEvent event) {
                updateProductQuantities(binding);
            }
        });

        //warehouse
        propDetails = entProps.getPropertyDetails("warehouse");
        warehouseField.bind(new AcaciaLookupProvider() {

            @Override
            public Object showSelectionControl() {
                return onChooseWarehous();
            }

        }, bindGroup,
        entity,
        propDetails,
        "${address.addressName}",
        UpdateStrategy.READ_WRITE);

        //quantityInStock
        qtyInStockField.bind(bindGroup, entity, entProps.getPropertyDetails("quantityInStock"))
            .addBindingListener(new FreeQuantityChangeListener());
        //orderedQuantity
        qtyOrderedField.bind(bindGroup, entity, entProps.getPropertyDetails("orderedQuantity"));
        //reservedQuantity
        qtyReservedField.bind(bindGroup, entity, entProps.getPropertyDetails("reservedQuantity"))
            .addBindingListener(new FreeQuantityChangeListener());
        //soldQuantity
        qtySoldField.bind(bindGroup, entity, entProps.getPropertyDetails("soldQuantity"))
            .addBindingListener(new FreeQuantityChangeListener());
        //quantityDue
        qtyDueField.bind(bindGroup, entity, entProps.getPropertyDetails("quantityDue"));

        //minimumQuantity
        minQtyField.bind(bindGroup, entity, entProps.getPropertyDetails("minimumQuantity"));
        //maximumQuantity
        maxQtyField.bind(bindGroup, entity, entProps.getPropertyDetails("maximumQuantity"));
        //defaultQuantity
        defaultQtyField.bind(bindGroup, entity, entProps.getPropertyDetails("defaultQuantity"));
        //sale price in current form
        final Binding salesPriceFieldBinding = salesPriceField.bind(bindGroup, entity, entProps.getPropertyDetails("salePrice"));
        salesPriceField.setEditable(false);

        pricingPanel = new WarehouseProductPricingPanel();
        //purchase price
        pricingPanel.getPurchasePriceField().bind(bindGroup, entity, entProps.getPropertyDetails("purchasePrice"));
        //sale price
        Binding pricingPanelSalesBinding = pricingPanel.getSalePriceField().bind(bindGroup, entity, entProps.getPropertyDetails("salePrice"));
        pricingPanelSalesBinding.addBindingListener(new AbstractBindingListener() {
            @Override
            public void targetChanged(Binding binding, PropertyStateEvent event) {
                Object newValue = binding.getTargetProperty().getValue(pricingPanel.getSalePriceField());
                salesPriceFieldBinding.getTargetProperty().setValue(salesPriceField, newValue);
            }
        });

        //delivery time
        deliveryTimeField.bind(bindGroup, entity, entProps.getPropertyDetails("deliveryTime"));

        //notes
        notesField.bind(bindGroup, entity, "notes");

        warehouseField.setEditable(false);
        qtyInStockField.setEditable(false);

        bindGroup.bind();
    }

    @SuppressWarnings("unchecked")
    protected void updateProductQuantities(Binding binding) {
        SimpleProduct product = entity.getProduct();

        maxFromProductField.setText("-");
        minFromProductField.setText("-");
        defaultFromProductField.setText("-");

        ObjectToStringConverter toString = new AcaciaToStringConverter();

        if ( product!=null && binding.isContentValid() ){
            BigDecimal maxQty = product.getMaximumQuantity();
            if ( maxQty!=null ){
                maxFromProductField.setText(toString.getPreferredStringForItem(maxQty));
            }
            BigDecimal minQty = product.getMinimumQuantity();
            if ( minQty!=null ){
                minFromProductField.setText(toString.getPreferredStringForItem(minQty));
            }
            BigDecimal defaultQty = product.getDefaultQuantity();
            if ( defaultQty!=null ){
                defaultFromProductField.setText(toString.getPreferredStringForItem(defaultQty));
            }
        }
    }

    protected Object onChooseProduct() {
        ProductsListPanel listPanel = new ProductsListPanel(getParentDataObjectId());
        DialogResponse dResponse = listPanel.showDialog(this);
        if ( DialogResponse.SELECT.equals(dResponse) ){
            return listPanel.getSelectedRowObject();
        }else{
            return null;
        }
    }

    private class FreeQuantityChangeListener extends AbstractBindingListener{
        @SuppressWarnings("unchecked")
        @Override
        public void bindingBecameBound(Binding binding) {
            updateFreeQuantityField(true);
        }

        @SuppressWarnings("unchecked")
        @Override
        public void targetChanged(Binding binding, PropertyStateEvent event) {
            updateFreeQuantityField(binding.isContentValid());
        }
    }


    protected Object onChooseWarehous() {
        WarehouseListPanel listPanel = new WarehouseListPanel(null);
        DialogResponse dResponse = listPanel.showDialog(this);
        if ( DialogResponse.SELECT.equals(dResponse) ){
            return listPanel.getSelectedRowObject();
        }else{
            return null;
        }
    }

    public void updateFreeQuantityField(boolean contentValid) {
        if ( !contentValid ){
            qtyFreeField.setText("");
        }else{
            ObjectToStringConverter ots = new AcaciaToStringConverter();
            BigDecimal freeQty = entity.getFreeQuantity();
            String display = ots.getPreferredStringForItem(freeQty);
            qtyFreeField.setText(display);
        }
    }

    protected WarehouseListRemote getFormSession() {
        if (formSession == null)
            formSession = getBean(WarehouseListRemote.class);

        return formSession;
    }

    @Action
    public void productPricingAction() {
        pricingPanel.setTitle(getResourceMap().getString("PricingPanel.title"));
        pricingPanel.showDialog(this);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.cosmos.swingb.JBLabel defaultFromProductField;
    private com.cosmos.swingb.JBTextField defaultQtyField;
    private com.cosmos.swingb.JBTextField deliveryTimeField;
    private com.cosmos.acacia.gui.EntityFormButtonPanel entityFormButtonPanel1;
    private com.cosmos.swingb.JBButton jBButton1;
    private com.cosmos.swingb.JBLabel jBLabel1;
    private com.cosmos.swingb.JBLabel jBLabel10;
    private com.cosmos.swingb.JBLabel jBLabel11;
    private com.cosmos.swingb.JBLabel jBLabel13;
    private com.cosmos.swingb.JBLabel jBLabel14;
    private com.cosmos.swingb.JBLabel jBLabel15;
    private com.cosmos.swingb.JBLabel jBLabel2;
    private com.cosmos.swingb.JBLabel jBLabel3;
    private com.cosmos.swingb.JBLabel jBLabel4;
    private com.cosmos.swingb.JBLabel jBLabel5;
    private com.cosmos.swingb.JBLabel jBLabel6;
    private com.cosmos.swingb.JBLabel jBLabel7;
    private com.cosmos.swingb.JBLabel jBLabel8;
    private com.cosmos.swingb.JBLabel jBLabel9;
    private com.cosmos.swingb.JBPanel jBPanel1;
    private com.cosmos.swingb.JBPanel jBPanel2;
    private com.cosmos.swingb.JBPanel jBPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.cosmos.swingb.JBLabel maxFromProductField;
    private com.cosmos.swingb.JBTextField maxQtyField;
    private com.cosmos.swingb.JBLabel minFromProductField;
    private com.cosmos.swingb.JBTextField minQtyField;
    private com.cosmos.swingb.JBTextPane notesField;
    private com.cosmos.acacia.gui.AcaciaLookup productField;
    private com.cosmos.swingb.JBTextField qtyDueField;
    private com.cosmos.swingb.JBTextField qtyFreeField;
    private com.cosmos.swingb.JBTextField qtyInStockField;
    private com.cosmos.swingb.JBTextField qtyOrderedField;
    private com.cosmos.swingb.JBTextField qtyReservedField;
    private com.cosmos.swingb.JBTextField qtySoldField;
    private com.cosmos.swingb.JBTextField salesPriceField;
    private com.cosmos.acacia.gui.AcaciaLookup warehouseField;
    // End of variables declaration//GEN-END:variables

    private WarehouseProductPricingPanel pricingPanel;

    public void setReadonlyMode(boolean readonly) {

        productField.setEditable(!readonly);
        minQtyField.setEditable(!readonly);
        maxQtyField.setEditable(!readonly);
        defaultQtyField.setEditable(!readonly);
        deliveryTimeField.setEditable(!readonly);
        notesField.setEditable(!readonly);
        entityFormButtonPanel1.setVisible(Button.Save, !readonly);

        pricingPanel.setReadonlyMode(readonly);

        if ( readonly )
            setTitle(getResourceMap().getString("Form.title.readonly"));
        else {
            setTitle(getResourceMap().getString("Form.title"));
        }
    }
}
