/*
 * CallbackTestPanel.java
 *
 * Created on 13 June 2008, 23:48
 */

package com.cosmos.acacia.crm.gui;

import com.cosmos.acacia.callback.CallbackHandler;
import com.cosmos.acacia.callback.CallbackImpl;
import com.cosmos.acacia.callback.CallbackRequest;
import com.cosmos.acacia.callback.CallbackResult;
import com.cosmos.acacia.crm.bl.contactbook.impl.CallbackTestRemote;
import com.cosmos.acacia.gui.AcaciaPanel;
import java.io.Serializable;
import java.math.BigInteger;
import javax.naming.InitialContext;
import javax.swing.JOptionPane;

/**
 *
 * @author  Bozhidar Bozhanov
 */
public class CallbackTestPanel extends AcaciaPanel {

    /** Creates new form CallbackTestPanel */
    public CallbackTestPanel(BigInteger id) {
        super(id);
        initComponents();
        initData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.cosmos.acacia.crm.gui.AcaciaApplication.class).getContext().getResourceMap(CallbackTestPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void initData() {
        
        this.jLabel1.setText("" + getFormSession().calculate(5, 6));
        this.jLabel2.setText("" + getFormSession().calculate(5, 0));
    }

    private CallbackTestRemote formSession;
    
    public CallbackTestRemote getFormSession() {
        if (formSession == null) {
            try {
                formSession = InitialContext.doLookup(CallbackTestRemote.class.getName());
                int id = formSession.prepareCallback();

                CallbackHandler handler = new TestCallbackHandler();
                CallbackImpl.getClientInstance(id, handler);
            } catch (Exception ex){
                ex.printStackTrace();
            }
        }
        return formSession;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}

class TestCallbackHandler implements CallbackHandler, Serializable {
    
    @Override
    public CallbackResult handle(CallbackRequest req) {
        CallbackResult result = new CallbackResult();
        String b = JOptionPane.showInputDialog(req.getParam("message"));
        result.addParam("response", b);
        return result;
    }
}
