/*
 * ProductCategoriesPanel.java
 *
 * Created on Четвъртък, 2008, Февруари 21, 17:01
 */

package com.cosmos.acacia.crm.gui;

import com.cosmos.acacia.crm.data.DataObject;
import com.cosmos.acacia.gui.AcaciaPanel;

/**
 *
 * @author  Miro
 */
public class ProductCategoriesPanel extends AcaciaPanel {
    
    /** Creates new form ProductCategoriesPanel */
    public ProductCategoriesPanel(DataObject parentDataObject) {
        super(parentDataObject);
        initComponents();
        initData();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productCategoriesSplitPane = new com.cosmos.swingb.JBSplitPane();
        productCategoriesTreeScrollPane = new javax.swing.JScrollPane();
        productCategoriesTree = new com.cosmos.swingb.JBTree();
        productCategoriesPanel = new com.cosmos.swingb.JBPanel();
        crudButtonPanel = new com.cosmos.acacia.gui.CRUDButtonPanel();
        productCategoriesTableScrollPane = new javax.swing.JScrollPane();
        productCategoriesTable = new com.cosmos.acacia.gui.AcaciaTable();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        productCategoriesSplitPane.setDividerLocation(150);
        productCategoriesSplitPane.setName("productCategoriesSplitPane"); // NOI18N

        productCategoriesTreeScrollPane.setName("productCategoriesTreeScrollPane"); // NOI18N

        productCategoriesTree.setName("productCategoriesTree"); // NOI18N
        productCategoriesTreeScrollPane.setViewportView(productCategoriesTree);

        productCategoriesSplitPane.setLeftComponent(productCategoriesTreeScrollPane);

        productCategoriesPanel.setName("productCategoriesPanel"); // NOI18N

        crudButtonPanel.setName("crudButtonPanel"); // NOI18N

        productCategoriesTableScrollPane.setName("productCategoriesTableScrollPane"); // NOI18N

        productCategoriesTable.setName("productCategoriesTable"); // NOI18N
        productCategoriesTableScrollPane.setViewportView(productCategoriesTable);

        javax.swing.GroupLayout productCategoriesPanelLayout = new javax.swing.GroupLayout(productCategoriesPanel);
        productCategoriesPanel.setLayout(productCategoriesPanelLayout);
        productCategoriesPanelLayout.setHorizontalGroup(
            productCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crudButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
            .addComponent(productCategoriesTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        productCategoriesPanelLayout.setVerticalGroup(
            productCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productCategoriesPanelLayout.createSequentialGroup()
                .addComponent(productCategoriesTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crudButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        productCategoriesSplitPane.setRightComponent(productCategoriesPanel);

        add(productCategoriesSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.cosmos.acacia.gui.CRUDButtonPanel crudButtonPanel;
    private com.cosmos.swingb.JBPanel productCategoriesPanel;
    private com.cosmos.swingb.JBSplitPane productCategoriesSplitPane;
    private com.cosmos.acacia.gui.AcaciaTable productCategoriesTable;
    private javax.swing.JScrollPane productCategoriesTableScrollPane;
    private com.cosmos.swingb.JBTree productCategoriesTree;
    private javax.swing.JScrollPane productCategoriesTreeScrollPane;
    // End of variables declaration//GEN-END:variables
    


    protected void initData()
    {
        
    }
}
