/*
 * ProductPanelNew.java
 *
 * Created on Неделя, 2009, Февруари 1, 15:20
 */

package com.cosmos.acacia.crm.gui;

import com.cosmos.acacia.gui.AbstractTablePanel;
import java.awt.BorderLayout;
import java.text.ParseException;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author  Miro
 */
public class ProductPanelNew extends javax.swing.JPanel {

    /** Creates new form ProductPanelNew */
    public ProductPanelNew() {
        initComponents();
        initData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productTabbedPane = new com.cosmos.swingb.JBTabbedPane();
        primaryInfoPanel = new com.cosmos.swingb.JBPanel();
        productNameTextField = new com.cosmos.swingb.JBTextField();
        productNameLabel = new com.cosmos.swingb.JBLabel();
        productCategoryComboList = new com.cosmos.acacia.gui.AcaciaComboList();
        productCategoryLabel = new com.cosmos.swingb.JBLabel();
        codeFormatTextField = new com.cosmos.swingb.JBTextField();
        codeFormatLabel = new com.cosmos.swingb.JBLabel();
        productCodeTextField = new com.cosmos.swingb.JBFormattedTextField();
        productCodeLabel = new com.cosmos.swingb.JBLabel();
        measureUnitComboBox = new com.cosmos.acacia.gui.AcaciaComboBox();
        measureUnitLabel = new com.cosmos.swingb.JBLabel();
        productColorComboBox = new com.cosmos.acacia.gui.AcaciaComboBox();
        productColorLabel = new com.cosmos.swingb.JBLabel();
        producerComboList = new com.cosmos.acacia.gui.AcaciaComboList();
        producerLabel = new com.cosmos.swingb.JBLabel();
        quantityPerPackageTextField = new com.cosmos.swingb.JBFormattedTextField();
        quantityPerPackageLabel = new com.cosmos.swingb.JBLabel();
        purchasedCheckBox = new com.cosmos.swingb.JBCheckBox();
        salableCheckBox = new com.cosmos.swingb.JBCheckBox();
        obsoleteCheckBox = new com.cosmos.swingb.JBCheckBox();
        pricePanel = new com.cosmos.swingb.JBPanel();
        pricePerQuantityTextField = new com.cosmos.swingb.JBFormattedTextField();
        salesPriceTextField = new com.cosmos.swingb.JBFormattedTextField();
        pricePerQuantityLabel = new com.cosmos.swingb.JBLabel();
        salesPriceLabel = new com.cosmos.swingb.JBLabel();
        quantitiesOnStockPanel = new com.cosmos.swingb.JBPanel();
        minLabeledTextField = new com.cosmos.swingb.LabeledTextField();
        defaultLabeledTextField = new com.cosmos.swingb.LabeledTextField();
        maxLabeledTextField = new com.cosmos.swingb.LabeledTextField();
        additionalInfoPanel = new com.cosmos.swingb.JBPanel();
        deliveryInfoPanel = new com.cosmos.swingb.JBPanel();
        weightLabeledTextField = new com.cosmos.swingb.LabeledTextField();
        deliveryTimeLabeledTextField = new com.cosmos.swingb.LabeledTextField();
        weightUnitComboBox = new com.cosmos.acacia.gui.AcaciaComboBox();
        weightUnitLabel = new com.cosmos.swingb.JBLabel();
        dimensionsPanel = new com.cosmos.swingb.JBPanel();
        dimensionUnitComboBox = new com.cosmos.acacia.gui.AcaciaComboBox();
        dimensionUnitLabel = new com.cosmos.swingb.JBLabel();
        dimensionValuesPanel = new com.cosmos.swingb.JBPanel();
        widthLabeledTextField = new com.cosmos.swingb.LabeledTextField();
        lengthLabeledTextField = new com.cosmos.swingb.LabeledTextField();
        heightLabeledTextField = new com.cosmos.swingb.LabeledTextField();
        cubageLabeledTextField = new com.cosmos.swingb.LabeledTextField();
        descriptionPanel = new com.cosmos.swingb.JBPanel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextPane = new com.cosmos.swingb.JBTextPane();
        productPricingPanel = new com.cosmos.swingb.JBPanel();
        suppliersPanel = new com.cosmos.swingb.JBPanel();
        buttonsPanel = new com.cosmos.swingb.JBPanel();
        closeButton = new com.cosmos.swingb.JBButton();
        saveButton = new com.cosmos.swingb.JBButton();

        setName("Form"); // NOI18N

        productTabbedPane.setName("productTabbedPane"); // NOI18N

        primaryInfoPanel.setName("primaryInfoPanel"); // NOI18N

        productNameTextField.setName("productNameTextField"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.cosmos.acacia.crm.gui.AcaciaApplication.class).getContext().getResourceMap(ProductPanelNew.class);
        productNameLabel.setText(resourceMap.getString("productNameLabel.text")); // NOI18N
        productNameLabel.setName("productNameLabel"); // NOI18N

        productCategoryComboList.setName("productCategoryComboList"); // NOI18N

        productCategoryLabel.setText(resourceMap.getString("productCategoryLabel.text")); // NOI18N
        productCategoryLabel.setName("productCategoryLabel"); // NOI18N

        codeFormatTextField.setName("codeFormatTextField"); // NOI18N
        codeFormatTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codeFormatTextFieldFocusLost(evt);
            }
        });

        codeFormatLabel.setText(resourceMap.getString("codeFormatLabel.text")); // NOI18N
        codeFormatLabel.setName("codeFormatLabel"); // NOI18N

        productCodeTextField.setName("productCodeTextField"); // NOI18N

        productCodeLabel.setText(resourceMap.getString("productCodeLabel.text")); // NOI18N
        productCodeLabel.setName("productCodeLabel"); // NOI18N

        measureUnitComboBox.setName("measureUnitComboBox"); // NOI18N

        measureUnitLabel.setText(resourceMap.getString("measureUnitLabel.text")); // NOI18N
        measureUnitLabel.setName("measureUnitLabel"); // NOI18N

        productColorComboBox.setName("productColorComboBox"); // NOI18N

        productColorLabel.setText(resourceMap.getString("productColorLabel.text")); // NOI18N
        productColorLabel.setName("productColorLabel"); // NOI18N

        producerComboList.setName("producerComboList"); // NOI18N

        producerLabel.setText(resourceMap.getString("producerLabel.text")); // NOI18N
        producerLabel.setName("producerLabel"); // NOI18N

        quantityPerPackageTextField.setName("quantityPerPackageTextField"); // NOI18N

        quantityPerPackageLabel.setText(resourceMap.getString("quantityPerPackageLabel.text")); // NOI18N
        quantityPerPackageLabel.setName("quantityPerPackageLabel"); // NOI18N

        purchasedCheckBox.setText(resourceMap.getString("purchasedCheckBox.text")); // NOI18N
        purchasedCheckBox.setName("purchasedCheckBox"); // NOI18N

        salableCheckBox.setText(resourceMap.getString("salableCheckBox.text")); // NOI18N
        salableCheckBox.setName("salableCheckBox"); // NOI18N

        obsoleteCheckBox.setText(resourceMap.getString("obsoleteCheckBox.text")); // NOI18N
        obsoleteCheckBox.setName("obsoleteCheckBox"); // NOI18N

        pricePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pricePanel.border.title"))); // NOI18N
        pricePanel.setName("pricePanel"); // NOI18N

        pricePerQuantityTextField.setName("pricePerQuantityTextField"); // NOI18N

        salesPriceTextField.setName("salesPriceTextField"); // NOI18N

        pricePerQuantityLabel.setText(resourceMap.getString("pricePerQuantityLabel.text")); // NOI18N
        pricePerQuantityLabel.setName("pricePerQuantityLabel"); // NOI18N

        salesPriceLabel.setText(resourceMap.getString("salesPriceLabel.text")); // NOI18N
        salesPriceLabel.setName("salesPriceLabel"); // NOI18N

        javax.swing.GroupLayout pricePanelLayout = new javax.swing.GroupLayout(pricePanel);
        pricePanel.setLayout(pricePanelLayout);
        pricePanelLayout.setHorizontalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pricePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pricePerQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salesPriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(pricePerQuantityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addContainerGap())
        );
        pricePanelLayout.setVerticalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pricePanelLayout.createSequentialGroup()
                .addGroup(pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pricePerQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pricePerQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salesPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        quantitiesOnStockPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("quantitiesOnStockPanel.border.title"))); // NOI18N
        quantitiesOnStockPanel.setName("quantitiesOnStockPanel"); // NOI18N
        quantitiesOnStockPanel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        minLabeledTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        minLabeledTextField.setLabelText(resourceMap.getString("minLabeledTextField.labelText")); // NOI18N
        minLabeledTextField.setText(resourceMap.getString("minLabeledTextField.text")); // NOI18N
        quantitiesOnStockPanel.add(minLabeledTextField);

        defaultLabeledTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        defaultLabeledTextField.setLabelText(resourceMap.getString("defaultLabeledTextField.labelText")); // NOI18N
        defaultLabeledTextField.setText(resourceMap.getString("defaultLabeledTextField.text")); // NOI18N
        quantitiesOnStockPanel.add(defaultLabeledTextField);

        maxLabeledTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        maxLabeledTextField.setLabelText(resourceMap.getString("maxLabeledTextField.labelText")); // NOI18N
        maxLabeledTextField.setText(resourceMap.getString("maxLabeledTextField.text")); // NOI18N
        quantitiesOnStockPanel.add(maxLabeledTextField);

        javax.swing.GroupLayout primaryInfoPanelLayout = new javax.swing.GroupLayout(primaryInfoPanel);
        primaryInfoPanel.setLayout(primaryInfoPanelLayout);
        primaryInfoPanelLayout.setHorizontalGroup(
            primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pricePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(primaryInfoPanelLayout.createSequentialGroup()
                        .addComponent(purchasedCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salableCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(obsoleteCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(primaryInfoPanelLayout.createSequentialGroup()
                        .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityPerPackageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(producerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(measureUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeFormatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(productCategoryComboList, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(codeFormatTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(productCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(measureUnitComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(productColorComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(producerComboList, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(quantityPerPackageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                    .addComponent(quantitiesOnStockPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addContainerGap())
        );
        primaryInfoPanelLayout.setVerticalGroup(
            primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(productCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productCategoryComboList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeFormatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeFormatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(measureUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(measureUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(producerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(producerComboList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityPerPackageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityPerPackageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(primaryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchasedCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salableCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obsoleteCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantitiesOnStockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        productTabbedPane.addTab(resourceMap.getString("primaryInfoPanel.TabConstraints.tabTitle"), primaryInfoPanel); // NOI18N

        additionalInfoPanel.setName("additionalInfoPanel"); // NOI18N

        deliveryInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("deliveryInfoPanel.border.title"))); // NOI18N
        deliveryInfoPanel.setName("deliveryInfoPanel"); // NOI18N

        weightLabeledTextField.setLabelText(resourceMap.getString("weightLabeledTextField.labelText")); // NOI18N
        weightLabeledTextField.setName("weightLabeledTextField"); // NOI18N
        weightLabeledTextField.setText(resourceMap.getString("weightLabeledTextField.text")); // NOI18N

        deliveryTimeLabeledTextField.setLabelText(resourceMap.getString("deliveryTimeLabeledTextField.labelText")); // NOI18N
        deliveryTimeLabeledTextField.setName("deliveryTimeLabeledTextField"); // NOI18N
        deliveryTimeLabeledTextField.setText(resourceMap.getString("deliveryTimeLabeledTextField.text")); // NOI18N

        weightUnitComboBox.setName("weightUnitComboBox"); // NOI18N

        weightUnitLabel.setText(resourceMap.getString("weightUnitLabel.text")); // NOI18N
        weightUnitLabel.setName("weightUnitLabel"); // NOI18N

        javax.swing.GroupLayout deliveryInfoPanelLayout = new javax.swing.GroupLayout(deliveryInfoPanel);
        deliveryInfoPanel.setLayout(deliveryInfoPanelLayout);
        deliveryInfoPanelLayout.setHorizontalGroup(
            deliveryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deliveryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryInfoPanelLayout.createSequentialGroup()
                        .addComponent(weightUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weightUnitComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                    .addGroup(deliveryInfoPanelLayout.createSequentialGroup()
                        .addComponent(weightLabeledTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(deliveryTimeLabeledTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))
                .addContainerGap())
        );
        deliveryInfoPanelLayout.setVerticalGroup(
            deliveryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryInfoPanelLayout.createSequentialGroup()
                .addGroup(deliveryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deliveryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightLabeledTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryTimeLabeledTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dimensionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("dimensionsPanel.border.title"))); // NOI18N
        dimensionsPanel.setName("dimensionsPanel"); // NOI18N

        dimensionUnitComboBox.setName("dimensionUnitComboBox"); // NOI18N

        dimensionUnitLabel.setText(resourceMap.getString("dimensionUnitLabel.text")); // NOI18N
        dimensionUnitLabel.setName("dimensionUnitLabel"); // NOI18N

        dimensionValuesPanel.setName("dimensionValuesPanel"); // NOI18N
        dimensionValuesPanel.setLayout(new java.awt.GridLayout(2, 2));

        widthLabeledTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 5));
        widthLabeledTextField.setLabelText(resourceMap.getString("widthLabeledTextField.labelText")); // NOI18N
        widthLabeledTextField.setName("widthLabeledTextField"); // NOI18N
        widthLabeledTextField.setText(resourceMap.getString("widthLabeledTextField.text")); // NOI18N
        dimensionValuesPanel.add(widthLabeledTextField);

        lengthLabeledTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 3, 0));
        lengthLabeledTextField.setLabelText(resourceMap.getString("lengthLabeledTextField.labelText")); // NOI18N
        lengthLabeledTextField.setName("lengthLabeledTextField"); // NOI18N
        lengthLabeledTextField.setText(resourceMap.getString("lengthLabeledTextField.text")); // NOI18N
        dimensionValuesPanel.add(lengthLabeledTextField);

        heightLabeledTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 0, 5));
        heightLabeledTextField.setLabelText(resourceMap.getString("heightLabeledTextField.labelText")); // NOI18N
        heightLabeledTextField.setName("heightLabeledTextField"); // NOI18N
        heightLabeledTextField.setText(resourceMap.getString("heightLabeledTextField.text")); // NOI18N
        dimensionValuesPanel.add(heightLabeledTextField);

        cubageLabeledTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 0, 0));
        cubageLabeledTextField.setLabelText(resourceMap.getString("cubageLabeledTextField.labelText")); // NOI18N
        cubageLabeledTextField.setName("cubageLabeledTextField"); // NOI18N
        cubageLabeledTextField.setText(resourceMap.getString("cubageLabeledTextField.text")); // NOI18N
        dimensionValuesPanel.add(cubageLabeledTextField);

        javax.swing.GroupLayout dimensionsPanelLayout = new javax.swing.GroupLayout(dimensionsPanel);
        dimensionsPanel.setLayout(dimensionsPanelLayout);
        dimensionsPanelLayout.setHorizontalGroup(
            dimensionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dimensionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dimensionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dimensionValuesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(dimensionsPanelLayout.createSequentialGroup()
                        .addComponent(dimensionUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dimensionUnitComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dimensionsPanelLayout.setVerticalGroup(
            dimensionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dimensionsPanelLayout.createSequentialGroup()
                .addGroup(dimensionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dimensionUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dimensionUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dimensionValuesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        descriptionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("descriptionPanel.border.title"))); // NOI18N
        descriptionPanel.setName("descriptionPanel"); // NOI18N
        descriptionPanel.setLayout(new java.awt.BorderLayout());

        descriptionScrollPane.setName("descriptionScrollPane"); // NOI18N

        descriptionTextPane.setName("descriptionTextPane"); // NOI18N
        descriptionScrollPane.setViewportView(descriptionTextPane);

        descriptionPanel.add(descriptionScrollPane, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout additionalInfoPanelLayout = new javax.swing.GroupLayout(additionalInfoPanel);
        additionalInfoPanel.setLayout(additionalInfoPanelLayout);
        additionalInfoPanelLayout.setHorizontalGroup(
            additionalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, additionalInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(additionalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descriptionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(deliveryInfoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dimensionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        additionalInfoPanelLayout.setVerticalGroup(
            additionalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(additionalInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deliveryInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dimensionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        productTabbedPane.addTab(resourceMap.getString("additionalInfoPanel.TabConstraints.tabTitle"), additionalInfoPanel); // NOI18N

        productPricingPanel.setName("productPricingPanel"); // NOI18N

        javax.swing.GroupLayout productPricingPanelLayout = new javax.swing.GroupLayout(productPricingPanel);
        productPricingPanel.setLayout(productPricingPanelLayout);
        productPricingPanelLayout.setHorizontalGroup(
            productPricingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        productPricingPanelLayout.setVerticalGroup(
            productPricingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        productTabbedPane.addTab(resourceMap.getString("productPricingPanel.TabConstraints.tabTitle"), productPricingPanel); // NOI18N

        suppliersPanel.setName("suppliersPanel"); // NOI18N
        suppliersPanel.setLayout(new java.awt.BorderLayout());
        productTabbedPane.addTab(resourceMap.getString("suppliersPanel.TabConstraints.tabTitle"), suppliersPanel); // NOI18N

        buttonsPanel.setName("buttonsPanel"); // NOI18N

        closeButton.setIcon(resourceMap.getIcon("closeButton.icon")); // NOI18N
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        saveButton.setIcon(resourceMap.getIcon("saveButton.icon")); // NOI18N
        saveButton.setText(resourceMap.getString("saveButton.text")); // NOI18N
        saveButton.setName("saveButton"); // NOI18N

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {closeButton, saveButton});

        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {closeButton, saveButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
            .addComponent(buttonsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(productTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void codeFormatTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeFormatTextFieldFocusLost
// TODO add your handling code here:
    codeFormatChanged();
}//GEN-LAST:event_codeFormatTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.cosmos.swingb.JBPanel additionalInfoPanel;
    private com.cosmos.swingb.JBPanel buttonsPanel;
    private com.cosmos.swingb.JBButton closeButton;
    private com.cosmos.swingb.JBLabel codeFormatLabel;
    private com.cosmos.swingb.JBTextField codeFormatTextField;
    private com.cosmos.swingb.LabeledTextField cubageLabeledTextField;
    private com.cosmos.swingb.LabeledTextField defaultLabeledTextField;
    private com.cosmos.swingb.JBPanel deliveryInfoPanel;
    private com.cosmos.swingb.LabeledTextField deliveryTimeLabeledTextField;
    private com.cosmos.swingb.JBPanel descriptionPanel;
    private javax.swing.JScrollPane descriptionScrollPane;
    private com.cosmos.swingb.JBTextPane descriptionTextPane;
    private com.cosmos.acacia.gui.AcaciaComboBox dimensionUnitComboBox;
    private com.cosmos.swingb.JBLabel dimensionUnitLabel;
    private com.cosmos.swingb.JBPanel dimensionValuesPanel;
    private com.cosmos.swingb.JBPanel dimensionsPanel;
    private com.cosmos.swingb.LabeledTextField heightLabeledTextField;
    private com.cosmos.swingb.LabeledTextField lengthLabeledTextField;
    private com.cosmos.swingb.LabeledTextField maxLabeledTextField;
    private com.cosmos.acacia.gui.AcaciaComboBox measureUnitComboBox;
    private com.cosmos.swingb.JBLabel measureUnitLabel;
    private com.cosmos.swingb.LabeledTextField minLabeledTextField;
    private com.cosmos.swingb.JBCheckBox obsoleteCheckBox;
    private com.cosmos.swingb.JBPanel pricePanel;
    private com.cosmos.swingb.JBLabel pricePerQuantityLabel;
    private com.cosmos.swingb.JBFormattedTextField pricePerQuantityTextField;
    private com.cosmos.swingb.JBPanel primaryInfoPanel;
    private com.cosmos.acacia.gui.AcaciaComboList producerComboList;
    private com.cosmos.swingb.JBLabel producerLabel;
    private com.cosmos.acacia.gui.AcaciaComboList productCategoryComboList;
    private com.cosmos.swingb.JBLabel productCategoryLabel;
    private com.cosmos.swingb.JBLabel productCodeLabel;
    private com.cosmos.swingb.JBFormattedTextField productCodeTextField;
    private com.cosmos.acacia.gui.AcaciaComboBox productColorComboBox;
    private com.cosmos.swingb.JBLabel productColorLabel;
    private com.cosmos.swingb.JBLabel productNameLabel;
    private com.cosmos.swingb.JBTextField productNameTextField;
    private com.cosmos.swingb.JBPanel productPricingPanel;
    private com.cosmos.swingb.JBTabbedPane productTabbedPane;
    private com.cosmos.swingb.JBCheckBox purchasedCheckBox;
    private com.cosmos.swingb.JBPanel quantitiesOnStockPanel;
    private com.cosmos.swingb.JBLabel quantityPerPackageLabel;
    private com.cosmos.swingb.JBFormattedTextField quantityPerPackageTextField;
    private com.cosmos.swingb.JBCheckBox salableCheckBox;
    private com.cosmos.swingb.JBLabel salesPriceLabel;
    private com.cosmos.swingb.JBFormattedTextField salesPriceTextField;
    private com.cosmos.swingb.JBButton saveButton;
    private com.cosmos.swingb.JBPanel suppliersPanel;
    private com.cosmos.swingb.LabeledTextField weightLabeledTextField;
    private com.cosmos.acacia.gui.AcaciaComboBox weightUnitComboBox;
    private com.cosmos.swingb.JBLabel weightUnitLabel;
    private com.cosmos.swingb.LabeledTextField widthLabeledTextField;
    // End of variables declaration//GEN-END:variables


    private SuppliersListPanel suppliersListPanel;
    private String lastCodeFormat;

    private void initData() {
        suppliersListPanel = new SuppliersListPanel();
        suppliersPanel.add(suppliersListPanel, BorderLayout.CENTER);
    }

    private void codeFormatChanged() {
        MaskFormatter formatter = (MaskFormatter)productCodeTextField.getFormatter();
        String codeFormat = codeFormatTextField.getText();
        System.out.println("codeFormat: " + codeFormat);
        System.out.println("lastCodeFormat: " + lastCodeFormat);

        System.out.println("productCodeTextField.getText(): " + productCodeTextField.getText());
        Object value = productCodeTextField.getValue();
        System.out.println("productCodeTextField.getValue(): " + value);

        if((codeFormat == null && lastCodeFormat == null) ||
                (codeFormat != null && codeFormat.equals(lastCodeFormat))) {
            return;
        }

        try {
            productCodeTextField.setValue("");
            formatter.setMask(codeFormat);
            lastCodeFormat = codeFormat;
        } catch(ParseException ex) {
            ex.printStackTrace();
            return;
        }

        try {
            productCodeTextField.setValue(value);
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }


    private class SuppliersListPanel extends AbstractTablePanel {

        @Override
        protected boolean deleteRow(Object rowObject) {
            return false;
        }

        @Override
        protected Object modifyRow(Object rowObject) {
            return null;
        }

        @Override
        protected Object newRow() {
            return null;
        }
        
    }
}
