/*
 * ProductPricingValueForm.java
 *
 * Created on Понеделник, 2008, Декември 22, 20:24
 */

package com.cosmos.acacia.crm.gui.pricing;

import org.jdesktop.beansbinding.BindingGroup;

import com.cosmos.acacia.crm.bl.pricing.ProductPricingValueRemote;
import com.cosmos.acacia.crm.data.product.ProductPercentValue;
import com.cosmos.acacia.gui.BaseEntityPanel;
import com.cosmos.acacia.gui.EntityFormButtonPanel;
import com.cosmos.beansbinding.EntityProperties;
import com.cosmos.swingb.DialogResponse;

/**
 * 
 * Created	:	02.01.2009
 * @author	Petar Milev
 *
 */
public class ProductPricingValueForm extends BaseEntityPanel {
    
    private ProductPercentValue entity;
    
    private BindingGroup bindingGroup;
    private ProductPricingValueRemote formSession = getBean(ProductPricingValueRemote.class);
    private EntityProperties entProps;
    
    /** Creates new form */
    public ProductPricingValueForm(ProductPercentValue entity) {
        super(entity.getParentId());
        this.entity = entity;
        if (entity.getType() != null) {
            setTitle(getResourceMap().getString("Form.title." + entity.getType()));
        }
        initialize();
    }
    
    private void initialize() {
        initComponents();
        initComponentsCustom();
        init();
    }

    private void initComponentsCustom() {
        if (entity.getType() != null) {
            valueNameLabel.setText(getResourceMap().getString("value.name." + entity.getType()));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueNameTextField = new com.cosmos.swingb.JBTextField();
        entityFormButtonPanel = new com.cosmos.acacia.gui.EntityFormButtonPanel();
        valueNameLabel = new com.cosmos.swingb.JBLabel();
        percentValueLabel = new com.cosmos.swingb.JBLabel();
        percentValuePercentField = new com.cosmos.swingb.JBPercentField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.cosmos.acacia.crm.gui.AcaciaApplication.class).getContext().getResourceMap(ProductPricingValueForm.class);
        valueNameTextField.setText(resourceMap.getString("valueNameTextField.text")); // NOI18N
        valueNameTextField.setName("valueNameTextField"); // NOI18N

        entityFormButtonPanel.setName("entityFormButtonPanel"); // NOI18N

        valueNameLabel.setText(resourceMap.getString("valueNameLabel.text")); // NOI18N
        valueNameLabel.setName("valueNameLabel"); // NOI18N

        percentValueLabel.setText(resourceMap.getString("percentValueLabel.text")); // NOI18N
        percentValueLabel.setName("percentValueLabel"); // NOI18N

        percentValuePercentField.setName("percentValuePercentField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entityFormButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(percentValuePercentField, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(valueNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentValuePercentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(entityFormButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.cosmos.acacia.gui.EntityFormButtonPanel entityFormButtonPanel;
    private com.cosmos.swingb.JBLabel percentValueLabel;
    private com.cosmos.swingb.JBPercentField percentValuePercentField;
    private com.cosmos.swingb.JBLabel valueNameLabel;
    private com.cosmos.swingb.JBTextField valueNameTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public BindingGroup getBindingGroup() {
        if(bindingGroup == null) {
            bindingGroup = new BindingGroup();
        }

        return bindingGroup;
    }

    @Override
    public EntityFormButtonPanel getButtonPanel() {
        return entityFormButtonPanel;
    }

    @Override
    public Object getEntity() {
        return entity;
    }

    @SuppressWarnings("deprecation")
    @Override
    public void performSave(boolean closeAfter) {
        entity = formSession.saveProductPricingValue(entity);
        setDialogResponse(DialogResponse.SAVE);
        setSelectedValue(entity);
        if (closeAfter) {
            close();
        } else {
            getBindingGroup().unbind();
            bindingGroup = null;
            initData();
        }
    }

    @Override
    protected void initData() {
        
        if (entProps == null)
            entProps = getFormSession().getDetailEntityProperties();

        BindingGroup bg = getBindingGroup();

        bindComponents(bg, entProps);
    }
    
    /**
     * Binds all components to the specified group and entity properties.
     * The group shouldn't be yet bound, or should be 'unbound'.
     * After all components are bound, some additional calculation and initialization is performed.
     */
    @SuppressWarnings("deprecation")
    protected void bindComponents(BindingGroup bindGroup, EntityProperties entProps) {
        // name 
        valueNameTextField.bind(bindGroup, entity, entProps.getEntityProperty("name"));
        
        // percentValue
        percentValuePercentField.bind(bindGroup, entity, entProps.getEntityProperty("percentValue"));
        
        bindGroup.bind();
    }
    
    @Override
    public void setReadonly() {
        super.setReadonly();
    }

    public ProductPricingValueRemote getFormSession() {
        return formSession;
    }
}