/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelatedDocumentSelectionPanel.java
 *
 * Created on 2009-4-10, 11:32:02
 */

package com.cosmos.acacia.crm.gui.purchase;

/**
 *
 * @author Miro
 */
public class RelatedDocumentSelectionPanel_1 extends javax.swing.JPanel {

    /** Creates new form RelatedDocumentSelectionPanel */
    public RelatedDocumentSelectionPanel_1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBTabbedPane1 = new com.cosmos.swingb.JBTabbedPane();
        purchaseInvoicePanel = new com.cosmos.swingb.JBPanel();
        goodsReturnPanel = new com.cosmos.swingb.JBPanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jBTabbedPane1.setName("jBTabbedPane1"); // NOI18N

        purchaseInvoicePanel.setName("purchaseInvoicePanel"); // NOI18N

        javax.swing.GroupLayout purchaseInvoicePanelLayout = new javax.swing.GroupLayout(purchaseInvoicePanel);
        purchaseInvoicePanel.setLayout(purchaseInvoicePanelLayout);
        purchaseInvoicePanelLayout.setHorizontalGroup(
            purchaseInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        purchaseInvoicePanelLayout.setVerticalGroup(
            purchaseInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.cosmos.acacia.crm.gui.AcaciaApplication.class).getContext().getResourceMap(RelatedDocumentSelectionPanel_1.class);
        jBTabbedPane1.addTab(resourceMap.getString("purchaseInvoicePanel.TabConstraints.tabTitle"), purchaseInvoicePanel); // NOI18N

        goodsReturnPanel.setName("goodsReturnPanel"); // NOI18N

        javax.swing.GroupLayout goodsReturnPanelLayout = new javax.swing.GroupLayout(goodsReturnPanel);
        goodsReturnPanel.setLayout(goodsReturnPanelLayout);
        goodsReturnPanelLayout.setHorizontalGroup(
            goodsReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        goodsReturnPanelLayout.setVerticalGroup(
            goodsReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jBTabbedPane1.addTab(resourceMap.getString("goodsReturnPanel.TabConstraints.tabTitle"), goodsReturnPanel); // NOI18N

        add(jBTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.cosmos.swingb.JBPanel goodsReturnPanel;
    private com.cosmos.swingb.JBTabbedPane jBTabbedPane1;
    private com.cosmos.swingb.JBPanel purchaseInvoicePanel;
    // End of variables declaration//GEN-END:variables

}
