/*
 * PurchaseOrderFormDraft.java
 *
 * Created on Петък, 2008, Юли 11, 17:34
 */

package com.cosmos.acacia.crm.gui.purchaseorders;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.math.BigInteger;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.swingbinding.JComboBoxBinding;

import com.cosmos.acacia.crm.bl.purchaseorder.PurchaseOrderListRemote;
import com.cosmos.acacia.crm.data.BusinessPartner;
import com.cosmos.acacia.crm.data.ContactPerson;
import com.cosmos.acacia.crm.data.DbResource;
import com.cosmos.acacia.crm.data.PurchaseOrder;
import com.cosmos.acacia.crm.enums.PurchaseOrderStatus;
import com.cosmos.acacia.crm.gui.contactbook.BusinessPartnersListPanel;
import com.cosmos.acacia.crm.reports.Report;
import com.cosmos.acacia.gui.AbstractTablePanel;
import com.cosmos.acacia.gui.BaseEntityPanel;
import com.cosmos.acacia.gui.EntityFormButtonPanel;
import com.cosmos.acacia.gui.EntityFormButtonPanel.Button;
import com.cosmos.beansbinding.EntityProperties;
import com.cosmos.beansbinding.PropertyDetails;
import com.cosmos.swingb.DialogResponse;

/**
 *
 * Created	:	14.07.2008
 * @author	Petar Milev
 * @version $Id: $
 *
 */
public class PurchaseOrderForm extends BaseEntityPanel {

    private PurchaseOrder entity;

    private EntityProperties entProps;

    private BindingGroup bindGroup;

    private PurchaseOrderListRemote formSession = getBean(PurchaseOrderListRemote.class);

    /** Creates new form PurchaseOrderFormDraft */
    public PurchaseOrderForm(PurchaseOrder order) {
        super(order.getParentId());
        this.entity = order;
        initialize();
    }

    private void initialize() {
        initComponents();
        intiComponentsCustom();
        init();
    }

    private void intiComponentsCustom() {
        // Using an AbstractTablePanel implementation
        itemsTablePanel = new PurchaseOrderItemListPanel(entity.getId());
        //branchesTable.setVisibleButtons(14); //Only New, Modify and Delete
        itemsTablePanel.setVisible(com.cosmos.acacia.gui.AbstractTablePanel.Button.Classify, false);
        itemsTablePanel.setVisible(com.cosmos.acacia.gui.AbstractTablePanel.Button.Refresh, false);
        itemsTablePanel.setVisible(com.cosmos.acacia.gui.AbstractTablePanel.Button.Close, false);
        itemsTablePanel.setEnabled(AbstractTablePanel.Button.Special, true);

        // Adding the nested table listener to ensure that purchase order is saved before adding
        //items to it.
        addNestedFormListener(itemsTablePanel);

        tableHolderPanel1.add(itemsTablePanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "unused" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBPanel1 = new com.cosmos.swingb.JBPanel();
        jBLabel6 = new com.cosmos.swingb.JBLabel();
        jBLabel3 = new com.cosmos.swingb.JBLabel();
        firstDeliveryField = new com.cosmos.swingb.JBTextField();
        jBLabel13 = new com.cosmos.swingb.JBLabel();
        lastDeliveryField = new com.cosmos.swingb.JBTextField();
        jBLabel14 = new com.cosmos.swingb.JBLabel();
        supplierField = new com.cosmos.acacia.gui.AcaciaComboList();
        supplierContactField = new com.cosmos.acacia.gui.AcaciaComboBox();
        jBPanel2 = new com.cosmos.swingb.JBPanel();
        jBLabel9 = new com.cosmos.swingb.JBLabel();
        jBLabel11 = new com.cosmos.swingb.JBLabel();
        jBLabel12 = new com.cosmos.swingb.JBLabel();
        sentAtField = new com.cosmos.swingb.JBTextField();
        jBLabel15 = new com.cosmos.swingb.JBLabel();
        finalizedAtField = new com.cosmos.swingb.JBTextField();
        creatorField = new com.cosmos.swingb.JBTextField();
        senderField = new com.cosmos.swingb.JBTextField();
        createdAtField = new com.cosmos.swingb.JBTextField();
        jBLabel19 = new com.cosmos.swingb.JBLabel();
        entityFormButtonPanel1 = new com.cosmos.acacia.gui.EntityFormButtonPanel();
        entityFormButtonPanel2 = new com.cosmos.acacia.gui.EntityFormButtonPanel();
        jBPanel3 = new com.cosmos.swingb.JBPanel();
        jBLabel5 = new com.cosmos.swingb.JBLabel();
        jBLabel1 = new com.cosmos.swingb.JBLabel();
        orderNumberField = new com.cosmos.swingb.JBTextField();
        supplierOrderNumberField = new com.cosmos.swingb.JBTextField();
        jBLabel8 = new com.cosmos.swingb.JBLabel();
        orderStatusField = new com.cosmos.acacia.gui.AcaciaComboBox();
        jBLabel2 = new com.cosmos.swingb.JBLabel();
        jBLabel10 = new com.cosmos.swingb.JBLabel();
        documentDeliveryField = new com.cosmos.acacia.gui.AcaciaComboBox();
        branchField = new com.cosmos.swingb.JBTextField();
        jBPanel4 = new com.cosmos.swingb.JBPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesField = new com.cosmos.swingb.JBTextPane();
        tableHolderPanel1 = new com.cosmos.acacia.gui.TableHolderPanel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.cosmos.acacia.crm.gui.AcaciaApplication.class).getContext().getResourceMap(PurchaseOrderForm.class);
        jBPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jBPanel1.border.title"))); // NOI18N
        jBPanel1.setName("jBPanel1"); // NOI18N

        jBLabel6.setText(resourceMap.getString("jBLabel6.text")); // NOI18N
        jBLabel6.setName("jBLabel6"); // NOI18N

        jBLabel3.setText(resourceMap.getString("jBLabel3.text")); // NOI18N
        jBLabel3.setName("jBLabel3"); // NOI18N

        firstDeliveryField.setEditable(false);
        firstDeliveryField.setName("firstDeliveryField"); // NOI18N
        firstDeliveryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstDeliveryFieldActionPerformed(evt);
            }
        });

        jBLabel13.setText(resourceMap.getString("jBLabel13.text")); // NOI18N
        jBLabel13.setName("jBLabel13"); // NOI18N

        lastDeliveryField.setEditable(false);
        lastDeliveryField.setName("lastDeliveryField"); // NOI18N
        lastDeliveryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastDeliveryFieldActionPerformed(evt);
            }
        });

        jBLabel14.setText(resourceMap.getString("jBLabel14.text")); // NOI18N
        jBLabel14.setName("jBLabel14"); // NOI18N

        supplierField.setName("supplierField"); // NOI18N

        supplierContactField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        supplierContactField.setName("supplierContactField"); // NOI18N

        javax.swing.GroupLayout jBPanel1Layout = new javax.swing.GroupLayout(jBPanel1);
        jBPanel1.setLayout(jBPanel1Layout);
        jBPanel1Layout.setHorizontalGroup(
            jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBPanel1Layout.createSequentialGroup()
                        .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jBLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(supplierContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBPanel1Layout.createSequentialGroup()
                        .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jBLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastDeliveryField, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(firstDeliveryField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jBPanel1Layout.setVerticalGroup(
            jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(supplierField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierContactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstDeliveryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastDeliveryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jBPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jBPanel2.border.title"))); // NOI18N
        jBPanel2.setName("jBPanel2"); // NOI18N

        jBLabel9.setText(resourceMap.getString("jBLabel9.text")); // NOI18N
        jBLabel9.setName("jBLabel9"); // NOI18N

        jBLabel11.setText(resourceMap.getString("jBLabel11.text")); // NOI18N
        jBLabel11.setName("jBLabel11"); // NOI18N

        jBLabel12.setText(resourceMap.getString("jBLabel12.text")); // NOI18N
        jBLabel12.setName("jBLabel12"); // NOI18N

        sentAtField.setEditable(false);
        sentAtField.setName("sentAtField"); // NOI18N
        sentAtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentAtFieldActionPerformed(evt);
            }
        });

        jBLabel15.setText(resourceMap.getString("jBLabel15.text")); // NOI18N
        jBLabel15.setName("jBLabel15"); // NOI18N

        finalizedAtField.setEditable(false);
        finalizedAtField.setName("finalizedAtField"); // NOI18N
        finalizedAtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizedAtFieldActionPerformed(evt);
            }
        });

        creatorField.setEditable(false);
        creatorField.setName("creatorField"); // NOI18N
        creatorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatorFieldActionPerformed(evt);
            }
        });

        senderField.setEditable(false);
        senderField.setName("senderField"); // NOI18N
        senderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senderFieldActionPerformed(evt);
            }
        });

        createdAtField.setEditable(false);
        createdAtField.setName("createdAtField"); // NOI18N
        createdAtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdAtFieldActionPerformed(evt);
            }
        });

        jBLabel19.setText(resourceMap.getString("jBLabel19.text")); // NOI18N
        jBLabel19.setName("jBLabel19"); // NOI18N

        javax.swing.GroupLayout jBPanel2Layout = new javax.swing.GroupLayout(jBPanel2);
        jBPanel2.setLayout(jBPanel2Layout);
        jBPanel2Layout.setHorizontalGroup(
            jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBPanel2Layout.createSequentialGroup()
                        .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jBLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jBPanel2Layout.createSequentialGroup()
                        .addComponent(jBLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(jBPanel2Layout.createSequentialGroup()
                        .addComponent(jBLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(jBPanel2Layout.createSequentialGroup()
                        .addComponent(jBLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalizedAtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(sentAtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(senderField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(creatorField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(createdAtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addContainerGap())
        );
        jBPanel2Layout.setVerticalGroup(
            jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creatorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdAtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(senderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sentAtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalizedAtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        entityFormButtonPanel1.setName("entityFormButtonPanel1"); // NOI18N

        entityFormButtonPanel2.setName("entityFormButtonPanel2"); // NOI18N

        jBPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jBPanel3.border.title"))); // NOI18N
        jBPanel3.setName("jBPanel3"); // NOI18N

        jBLabel5.setText(resourceMap.getString("jBLabel5.text")); // NOI18N
        jBLabel5.setName("jBLabel5"); // NOI18N

        jBLabel1.setText(resourceMap.getString("jBLabel1.text")); // NOI18N
        jBLabel1.setName("jBLabel1"); // NOI18N

        orderNumberField.setEditable(false);
        orderNumberField.setName("orderNumberField"); // NOI18N
        orderNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNumberFieldActionPerformed(evt);
            }
        });

        supplierOrderNumberField.setEditable(false);
        supplierOrderNumberField.setText(resourceMap.getString("supplierOrderNumberField.text")); // NOI18N
        supplierOrderNumberField.setName("supplierOrderNumberField"); // NOI18N
        supplierOrderNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierOrderNumberFieldActionPerformed(evt);
            }
        });

        jBLabel8.setText(resourceMap.getString("jBLabel8.text")); // NOI18N
        jBLabel8.setName("jBLabel8"); // NOI18N

        orderStatusField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orderStatusField.setEnabled(false);
        orderStatusField.setName("orderStatusField"); // NOI18N

        jBLabel2.setText(resourceMap.getString("jBLabel2.text")); // NOI18N
        jBLabel2.setName("jBLabel2"); // NOI18N

        jBLabel10.setText(resourceMap.getString("jBLabel10.text")); // NOI18N
        jBLabel10.setName("jBLabel10"); // NOI18N

        documentDeliveryField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        documentDeliveryField.setName("documentDeliveryField"); // NOI18N

        branchField.setEditable(false);
        branchField.setName("branchField"); // NOI18N
        branchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBPanel3Layout = new javax.swing.GroupLayout(jBPanel3);
        jBPanel3.setLayout(jBPanel3Layout);
        jBPanel3Layout.setHorizontalGroup(
            jBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jBLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jBLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orderStatusField, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(supplierOrderNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(orderNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jBLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(branchField, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(documentDeliveryField, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                .addContainerGap())
        );
        jBPanel3Layout.setVerticalGroup(
            jBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel3Layout.createSequentialGroup()
                .addGroup(jBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierOrderNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentDeliveryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jBPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jBPanel4.border.title"))); // NOI18N
        jBPanel4.setName("jBPanel4"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        notesField.setName("notesField"); // NOI18N
        jScrollPane1.setViewportView(notesField);

        javax.swing.GroupLayout jBPanel4Layout = new javax.swing.GroupLayout(jBPanel4);
        jBPanel4.setLayout(jBPanel4Layout);
        jBPanel4Layout.setHorizontalGroup(
            jBPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
                .addContainerGap())
        );
        jBPanel4Layout.setVerticalGroup(
            jBPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        tableHolderPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("tableHolderPanel1.border.title"))); // NOI18N
        tableHolderPanel1.setName("tableHolderPanel1"); // NOI18N

        javax.swing.GroupLayout tableHolderPanel1Layout = new javax.swing.GroupLayout(tableHolderPanel1);
        tableHolderPanel1.setLayout(tableHolderPanel1Layout);
        tableHolderPanel1Layout.setHorizontalGroup(
            tableHolderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        tableHolderPanel1Layout.setVerticalGroup(
            tableHolderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tableHolderPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(entityFormButtonPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                    .addComponent(jBPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableHolderPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entityFormButtonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void supplierOrderNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierOrderNumberFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_supplierOrderNumberFieldActionPerformed

private void orderNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNumberFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_orderNumberFieldActionPerformed

private void sentAtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentAtFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_sentAtFieldActionPerformed

private void finalizedAtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizedAtFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_finalizedAtFieldActionPerformed

private void creatorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatorFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_creatorFieldActionPerformed

private void senderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_senderFieldActionPerformed

private void createdAtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdAtFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_createdAtFieldActionPerformed

private void lastDeliveryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastDeliveryFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_lastDeliveryFieldActionPerformed

private void firstDeliveryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstDeliveryFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_firstDeliveryFieldActionPerformed

private void branchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_branchFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.cosmos.swingb.JBTextField branchField;
    private com.cosmos.swingb.JBTextField createdAtField;
    private com.cosmos.swingb.JBTextField creatorField;
    private com.cosmos.acacia.gui.AcaciaComboBox documentDeliveryField;
    private com.cosmos.acacia.gui.EntityFormButtonPanel entityFormButtonPanel1;
    private com.cosmos.acacia.gui.EntityFormButtonPanel entityFormButtonPanel2;
    private com.cosmos.swingb.JBTextField finalizedAtField;
    private com.cosmos.swingb.JBTextField firstDeliveryField;
    private com.cosmos.swingb.JBLabel jBLabel1;
    private com.cosmos.swingb.JBLabel jBLabel10;
    private com.cosmos.swingb.JBLabel jBLabel11;
    private com.cosmos.swingb.JBLabel jBLabel12;
    private com.cosmos.swingb.JBLabel jBLabel13;
    private com.cosmos.swingb.JBLabel jBLabel14;
    private com.cosmos.swingb.JBLabel jBLabel15;
    private com.cosmos.swingb.JBLabel jBLabel19;
    private com.cosmos.swingb.JBLabel jBLabel2;
    private com.cosmos.swingb.JBLabel jBLabel3;
    private com.cosmos.swingb.JBLabel jBLabel5;
    private com.cosmos.swingb.JBLabel jBLabel6;
    private com.cosmos.swingb.JBLabel jBLabel8;
    private com.cosmos.swingb.JBLabel jBLabel9;
    private com.cosmos.swingb.JBPanel jBPanel1;
    private com.cosmos.swingb.JBPanel jBPanel2;
    private com.cosmos.swingb.JBPanel jBPanel3;
    private com.cosmos.swingb.JBPanel jBPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.cosmos.swingb.JBTextField lastDeliveryField;
    private com.cosmos.swingb.JBTextPane notesField;
    private com.cosmos.swingb.JBTextField orderNumberField;
    private com.cosmos.acacia.gui.AcaciaComboBox orderStatusField;
    private com.cosmos.swingb.JBTextField senderField;
    private com.cosmos.swingb.JBTextField sentAtField;
    private com.cosmos.acacia.gui.AcaciaComboBox supplierContactField;
    private com.cosmos.acacia.gui.AcaciaComboList supplierField;
    private com.cosmos.swingb.JBTextField supplierOrderNumberField;
    private com.cosmos.acacia.gui.TableHolderPanel tableHolderPanel1;
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings("unchecked")
    JComboBoxBinding supplierContactBinding;

    private PurchaseOrderItemListPanel itemsTablePanel;

    private List<DbResource> statuses;

    private List<DbResource> deliveryMethods;

    @Override
    public BindingGroup getBindingGroup() {
        return bindGroup;
    }

    @Override
    public EntityFormButtonPanel getButtonPanel() {
        return entityFormButtonPanel2;
    }

    @Override
    public Object getEntity() {
        return entity;
    }

    @SuppressWarnings("unchecked")
    @Override
    public void performSave(boolean closeAfter) {
        updateSupplierContactName();

        entity = getFormSession().savePurchaseOrder(entity);
        setDialogResponse(DialogResponse.SAVE);
        setSelectedValue(entity);
        if (closeAfter)
            close();
        else{
            bindGroup.unbind();
            for (Binding binding : bindGroup.getBindings()) {
                bindGroup.removeBinding(binding);
            }
            initData();
            getButtonPanel().setSaveActionState(this);
        }
    }

    @SuppressWarnings("unchecked")
    @Override
    protected void initData() {

        if ( entProps==null )
            entProps = getFormSession().getDetailEntityProperties();

        if ( bindGroup==null )
            bindGroup = new BindingGroup();

        //if already persisted form - then the supplier can't be changed
        if ( entity.getOrderNumber()!=null &&  entity.getOrderNumber().compareTo(new BigInteger("0"))>0 ){
            entProps.getPropertyDetails("supplier").setReadOnly(true);
            entProps.getPropertyDetails("supplier").setEditable(false);
        }

        //order number
        PropertyDetails pd = entProps.getPropertyDetails("orderNumber");
        pd.setRequired(false);
        pd.setValidator(null);
        orderNumberField.bind(bindGroup, entity, pd);
        //supplier order number
        supplierOrderNumberField.bind(bindGroup, entity, entProps.getPropertyDetails("supplierOrderNumber"));
        //order status
        orderStatusField.bind(bindGroup, getPurchaseOrderStatuses(), entity, entProps.getPropertyDetails("status"));
        //branch
        branchField.bind(bindGroup, entity, entProps.getPropertyDetails("branchName"));
        //document delivery
        documentDeliveryField.bind(bindGroup, getDeliveryMethods(), entity, entProps.getPropertyDetails("documentDeliveryMethod"));

        //clear explicitly any items
        supplierContactField.setModel(new DefaultComboBoxModel());

        //supplier
        BusinessPartnersListPanel listPanel = BusinessPartnersListPanel.createProvidersPanel(getParentDataObjectId());
        supplierField.bind(
            bindGroup,
            listPanel,
            entity,
            entProps.getPropertyDetails("supplier"),
            "${displayName}",
            UpdateStrategy.READ_WRITE);
        supplierField.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                onSelectSupplier();
            }
        });

        if ( entity.getOrderNumber()!=null && entity.getOrderNumber().compareTo(new BigInteger("0"))>0 ){
            supplierField.setEditable(false);
            supplierField.setEnabled(false);
        }

        //supplier contact
        supplierContactBinding = supplierContactField.bind(bindGroup, getSupplierContacts(), entity, entProps.getPropertyDetails("supplierContact"));
        onSelectSupplier();

        DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.MEDIUM);

        //creator
        creatorField.bind(bindGroup, entity, entProps.getPropertyDetails("creatorName"));

        //creation time
        createdAtField.setText(dateFormat.format(entity.getCreationTime()));

        //sender
        senderField.bind(bindGroup, entity, entProps.getPropertyDetails("senderName"));

        //sent at
        if ( entity.getSentTime()!=null )
            sentAtField.setText(dateFormat.format(entity.getSentTime()));

        //fin at
        if ( entity.getFinalizingTime()!=null )
            finalizedAtField.setText(dateFormat.format(entity.getFinalizingTime()));

        //first delivery at
        if ( entity.getFirstDeliveryTime()!=null )
            firstDeliveryField.setText(dateFormat.format(entity.getFirstDeliveryTime()));

        //last delivery at
        if ( entity.getLastDeliveryTime()!=null )
            lastDeliveryField.setText(dateFormat.format(entity.getLastDeliveryTime()));

        //notes
        notesField.bind(bindGroup, entity, entProps.getPropertyDetails("notes"));

        boolean statusOpen = entity.getStatus()==null || entity.getStatus().getEnumValue()==PurchaseOrderStatus.Open;

        //if the order is in OPEN status, show 'sent order' button
        //PurchaseOrderStatus currentStatus = getFormSession().getOrderStatus(entity);
        if ( statusOpen ){
            entityFormButtonPanel2.getCustomButton().setText(getResourceMap().getString("customButton.text"));
            entityFormButtonPanel2.setVisible(Button.Custom, true);
            entityFormButtonPanel2.getCustomButton().addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    onSendButton();
                }
            });
        }else{
            itemsTablePanel.setReadonly();

            entProps.getPropertyDetails("supplierContact").setReadOnly(true);
        }

        bindGroup.bind();
    }

    protected void onInsertFromDocument() {

    }

    protected void onSendButton() {
        if ( itemsTablePanel.getListData()==null || itemsTablePanel.getListData().isEmpty() ){
            JOptionPane.showMessageDialog(
                this.getParent(),
                getResourceMap().getString("message.cannotsentempty"),
                getResourceMap().getString("message.cannotsentempty.title"),
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if ( showConfirmationDialog(getResourceMap().getString("sendButton.confirm"))){
            try {
                entity = getFormSession().updateOrderStatus(entity, PurchaseOrderStatus.Sent);
                setDialogResponse(DialogResponse.SAVE);
                setSelectedValue(entity);
                close();
            } catch (Exception ex){
                checkForValidationException(ex);
            }
        }
    }

    protected void updateSupplierContactName() {
        ContactPerson supplierContact = entity.getSupplierContact();
        if ( supplierContact==null )
            entity.setSupplierContactName(null);
        else
            entity.setSupplierContactName(supplierContact.getContact().getDisplayName());
    }

    private List<ContactPerson> getSupplierContacts() {
        Object supplier = supplierField.getSelectedItem();
        if ( ! ( supplier instanceof BusinessPartner) )
            return new ArrayList<ContactPerson>();
        else
            return getFormSession().getSupplierContacts((BusinessPartner) supplier);
    }

    protected void onSelectSupplier() {
        bindGroup.removeBinding(supplierContactBinding);
        supplierContactBinding = supplierContactField.bind(bindGroup, getSupplierContacts(), entity, entProps.getPropertyDetails("supplierContact"));
        supplierContactBinding.bind();

        //update the supplier name
        if ( entity.getSupplier()!=null )
            entity.setSupplierName(entity.getSupplier().getDisplayName());
        else
            entity.setSupplierName(null);

        //auto select if one choice is available
        if ( supplierContactField.getModel().getSize()==1 ){
            supplierContactField.setSelectedIndex(0);
        }else{
            supplierContactField.setSelectedIndex(-1);
        }
    }

    private List<DbResource> getPurchaseOrderStatuses() {
        if ( statuses==null )
            statuses = getFormSession().getStatuses();
        return statuses;
    }

    private List<DbResource> getDeliveryMethods() {
        if ( deliveryMethods==null )
            deliveryMethods = getFormSession().getDeliveryMethods();
        return deliveryMethods;
    }

    public PurchaseOrderListRemote getFormSession() {
        return formSession;
    }

    @Override
    public void setReadonly() {
        super.setReadonly();
        itemsTablePanel.setReadonly();
        getButtonPanel().getButton(Button.Custom).setVisible(false);
    }

    @Override
    protected Report getReport() {
        Report report = new Report("purchase_order", itemsTablePanel.getItems(), null);
        return report;
    }
}
